package com.justjava.humanresource.request.workflow.delegate;
import com.justjava.humanresource.approval.enums.ApprovalRouteType;
import com.justjava.humanresource.request.entity.*;
import com.justjava.humanresource.request.enums.*;
import com.justjava.humanresource.request.repository.*;
import com.justjava.humanresource.utils.AfterCommitExecutor;
import com.justjava.humanresource.utils.RequestEmailService;
import lombok.RequiredArgsConstructor;
import org.flowable.engine.delegate.*;
import org.springframework.stereotype.Component;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;
@Component("processRequestApprovalDecisionDelegate") @RequiredArgsConstructor public class ProcessRequestApprovalDecisionDelegate implements JavaDelegate {
 private final WorkflowRequestRepository requests; private final WorkflowRequestApprovalStepRepository steps; private final WorkflowRequestActivityRepository activities; private final RequestEmailService requestEmailService; private final AfterCommitExecutor afterCommitExecutor;
 public void execute(DelegateExecution e){Long id=((Number)e.getVariable("workflowRequestId")).longValue();WorkflowRequest r=requests.findById(id).orElseThrow();int level=((Number)e.getVariable("currentLevel")).intValue();int base=((Number)e.getVariable("approvalSequenceBase")).intValue();String action=String.valueOf(e.getVariable("approvalDecision"));Long actor=((Number)e.getVariable("approvalActorId")).longValue();boolean freeRoute=r.getApprovalRouteType()==ApprovalRouteType.FREE_ROUTE;WorkflowRequestApprovalStep step=resolveStep(id,r,base,level,actor,freeRoute);if(!step.getApproverEmployeeId().equals(actor))throw new IllegalStateException("Approval actor does not match configured approver.");step.setDecision(switch(action){case "APPROVE"->ApprovalDecision.APPROVED;case "REJECT"->ApprovalDecision.REJECTED;case "RETURN"->ApprovalDecision.RETURNED;default->throw new IllegalArgumentException("Unknown approval decision: "+action);});step.setComments((String)e.getVariable("approvalComment"));step.setDecisionAt(LocalDateTime.now());step.setFlowableTaskId((String)e.getVariable("flowableTaskId"));steps.save(step);if("APPROVE".equals(action)){if(freeRoute){e.setVariable("hasMoreApprovers",false);}else{List<?> approvers=(List<?>)e.getVariable("approverIds");boolean more=level<approvers.size();e.setVariable("hasMoreApprovers",more);if(more){int next=level+1;e.setVariable("currentLevel",next);e.setVariable("currentApproverId",String.valueOf(approvers.get(next-1)));r.setCurrentApprovalLevel(next);requests.save(r);Long nextApproverId=Long.valueOf(String.valueOf(approvers.get(next-1)));WorkflowRequest notificationRequest=r;afterCommitExecutor.runAfterCommit(()->{requestEmailService.notifyRequestMovedToApprover(notificationRequest,nextApproverId);requestEmailService.notifyPendingApproval(notificationRequest,nextApproverId);});}}}else e.setVariable("hasMoreApprovers",false);record(id,action,actor);}
 private WorkflowRequestApprovalStep resolveStep(Long id,WorkflowRequest r,int base,int level,Long actor,boolean freeRoute){if(!freeRoute)return steps.findByWorkflowRequestIdAndSequenceNo(id,base+level).orElseThrow();Integer currentLevel=r.getCurrentApprovalLevel();Optional<WorkflowRequestApprovalStep> primary=currentLevel==null?Optional.empty():steps.findByWorkflowRequestIdAndSequenceNo(id,currentLevel);return primary.or(()->steps.findByWorkflowRequestIdOrderBySequenceNo(id).stream().filter(s->s.getDecision()==ApprovalDecision.PENDING&&s.getApproverEmployeeId().equals(actor)).reduce((a,b)->b)).orElseThrow(()->new IllegalStateException("No pending Free Route approval step found for actor "+actor));}
 private void record(Long id,String action,Long actor){WorkflowRequestActivity a=new WorkflowRequestActivity();a.setWorkflowRequestId(id);a.setActivityType(switch(action){case "APPROVE"->RequestActivityType.APPROVED;case "REJECT"->RequestActivityType.REJECTED;default->RequestActivityType.RETURNED;});a.setDescription("Approval decision: "+action);a.setActorEmployeeId(actor);activities.save(a);}
}